before_install: before_install: echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
language: php
php:
  - 5.6
services:
  - redis-server
before_script:
  - composer install
script: vendor/bin/phpunit -v