before_install:
  - phpenv config-rm xdebug.ini
language: php
php:
  - 5.6
services:
  - redis-server
before_script:
  - composer install
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: vendor/bin/phpunit -v